version: '3.9'
services:
  url-service:
    build:
      context: url_shortener
    container_name: urlshortener
    env_file:
      - ./.env
    ports:
      - "50051:50051"
  db:
    image: "postgres:14"
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./persistence/db/data:/var/lib/postgresql/data
#  api-service:
#    build:
#      context: apiservice
#    depends_on:
#      - db
#    env_file:
#      - ./apiservice/.env
#    ports:
#      - "8090:8090"


