version: '3.9'
services:
  db:
    image: "postgres:14"
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./persistence/init/:/docker-entrypoint-initdb.d
      - ./persistence/db/data:/var/lib/postgresql/data
  url-service:
    build:
      context: .
    container_name: urlservice
    restart: always
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
